# Generated by Django 2.2.7 on 2019-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='sections',
            new_name='instructing_sections',
        ),
        migrations.AddField(
            model_name='student',
            name='course_sections',
            field=models.ManyToManyField(to='influx_tms.Section'),
        ),
    ]
