# Generated by Django 2.2.7 on 2019-11-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='institution_id',
            new_name='instructor_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='institution_id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influx_tms.Institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influx_tms.Institution'),
        ),
    ]
