# Generated by Django 2.2.7 on 2019-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0002_auto_20191128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='min_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
