# Generated by Django 2.2.7 on 2019-11-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0003_auto_20191130_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='liasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influx_tms.Student'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_students',
            field=models.IntegerField(default=4),
        ),
    ]
