# Generated by Django 2.2.7 on 2019-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0004_auto_20191130_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pending_students',
            field=models.ManyToManyField(related_name='pending_students', to='influx_tms.Student'),
        ),
    ]
