# Generated by Django 2.2.7 on 2019-12-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0005_team_pending_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_student_default',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='min_student_default',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pending_students',
            field=models.ManyToManyField(blank=True, related_name='pending_students', to='influx_tms.Student'),
        ),
    ]
