# Generated by Django 2.2.7 on 2019-12-02 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0007_course_creation_date_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creation_date_default',
        ),
        migrations.AddField(
            model_name='course',
            name='creation_deadline_default',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 1, 1), verbose_name='creation deadline default'),
        ),
    ]
