# Generated by Django 2.2.7 on 2019-12-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influx_tms', '0008_auto_20191202_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=20),
        ),
    ]
